steps:
  # Build the enhanced ESM container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/greenlane-crm-app:latest', '-f', 'Dockerfile.esm-enhanced', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/greenlane-crm-app:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${_APP_NAME}'
    - '--image=gcr.io/$PROJECT_ID/greenlane-crm-app:latest'
    - '--region=${_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--concurrency=80'
    - '--max-instances=10'
    - '--min-instances=1'
    - '--timeout=600s'
    - '--set-env-vars=NODE_ENV=production,HOST=0.0.0.0,DATABASE_URL=${_DATABASE_URL},BASE_DOMAIN=greenlanecloudsolutions.com'
    - '--add-cloudsql-instances=greenlane-cloud-solutions:us-central1:greenlanecrmdb'
    - '--quiet'

# Tag the image
images:
  - 'gcr.io/$PROJECT_ID/greenlane-crm-app:latest'

# Default substitution values
substitutions:
  _APP_NAME: greenlane-crm-app
  _REGION: us-central1
  _DATABASE_URL: ''
