steps:
  # Build the enhanced ESM container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/greenlane-crm-esm-enhanced:$COMMIT_SHA', '-f', 'Dockerfile.esm-enhanced', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/greenlane-crm-esm-enhanced:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'greenlane-crm-esm-enhanced'
    - '--image=gcr.io/$PROJECT_ID/greenlane-crm-esm-enhanced:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'
    - '--cpu=1'
    - '--concurrency=80'
    - '--max-instances=10'
    - '--min-instances=1'
    - '--timeout=300s'
    - '--set-env-vars=NODE_ENV=production,HOST=0.0.0.0'
    - '--quiet'

# Tag the image with the commit hash and 'latest'
images:
  - 'gcr.io/$PROJECT_ID/greenlane-crm-esm-enhanced:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/greenlane-crm-esm-enhanced:latest'

timeout: '1800s' # 30 minute timeout