steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/greenlane-cloud-solutions/greenlane-minimal-app', '-f', 'Dockerfile.minimal', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/greenlane-cloud-solutions/greenlane-minimal-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'greenlane-minimal-app'
      - '--image'
      - 'gcr.io/greenlane-cloud-solutions/greenlane-minimal-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'

images:
  - 'gcr.io/greenlane-cloud-solutions/greenlane-minimal-app'