steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/greenlane-crm-esm:$COMMIT_SHA', 
           '-f', 'Dockerfile.esm', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/greenlane-crm-esm:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'greenlane-crm-esm'
    - '--image=gcr.io/$PROJECT_ID/greenlane-crm-esm:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--memory=1Gi'
    - '--timeout=300s'
    - '--set-env-vars=NODE_ENV=production,HOST=0.0.0.0'
images:
  - 'gcr.io/$PROJECT_ID/greenlane-crm-esm:$COMMIT_SHA'